// src/pages/popup/app.tsx
const App = () => {
  return (
    <div className="absolute inset-0 bg-black p-4 text-center">
      <header className="text-white">
        <p>
          Edit <code>src/pages/popup/popup.tsx</code> and save to reload.
        </p>
        <a
          className="text-blue-700"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React!
        </a>
      </header>
    </div>
  );
};

export default App;

// src/pages/popup/App.svelte
<div class="absolute inset-0 bg-black p-4 text-center">
  <header class="text-white">
    <p>
      Edit <code>src/pages/popup/popup.tsx</code> and save to reload.
    </p>
    <a
      class="text-blue-700"
      href="https://reactjs.org"
      target="_blank"
      rel="noopener noreferrer"
    >
      Learn React!
    </a>
  </header>
</div>
